site_name: Orb Dynamic Edge Observability
theme:
  name: material
  custom_dir: overrides
  favicon: img/ORB-logo-ring.png
  logo: img/ORB-logo-ring.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - abbr
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
plugins:
  - search
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Installation: 'install.md'
  - Getting Started: 'getting_started.md'
  - Documentation:
    - Running ORB agent: 'documentation/running_orb_agent.md'
    - Advanced Policies: 'documentation/advanced_policies.md'
    - Orb REST API: 'api/orb_rest_api.md'
  - Community: 'contact.md'
repo_url: https://github.com/ns1labs/orb
edit_uri: edit/main/docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ns1labs/orb
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ns1labs
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/ns1labs/shared_invite/zt-qqsm5cb4-9fsq1xa~R3h~nX6W0sJzmA
    - icon: octicons/mail-24
      link: "mailto:info@pktvisor.dev"
  analytics:
    provider: google
    property: UA-41778111-9
copyright: Copyright &copy; 2022 <a href="https://ns1.com/labs">NS1</a>
