site_name: Orb Observability Platform
theme:
  name: material
  favicon: img/ORB-logo-ring.png
  logo: img/ORB-logo-ring.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Install: 'install.md'
  - Resources: 'docs.md'
  - Follow: 'contact.md'
repo_url: https://github.com/ns1labs/orb
repo_name: ns1labs/orb
edit_uri: ""
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ns1labs/orb
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ns1labs
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/ns1labs/shared_invite/zt-p0uzy9zq-ZgD~QkKQ9cWMSiI4DgJSaA
    - icon: octicons/mail-24
      link: "mailto:info@pktvisor.dev"
google_analytics:
  - UA-41778111-9
  - auto
copyright: Copyright &copy; 2021 <a href="https://ns1.com/labs">NS1</a>